version: '3.9'

services:
  app:
    build: ./django
    expose:
      - 8000
    command: "gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./django:/usr/src/app
      - static_files:/usr/src/app/staticfiles
    depends_on:
      - pg_db
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_files:/home/app/staticfiles
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    
  pg_db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/data:/var/lib/postgres/data
    ports:
      - 5432:5432
volumes:
  static_files:
  