databases:
  - name: app
    databaseName: mydb

services:
  - type: web
    name: app
    runtime: docker
    dockerfilePath: ./django
    # envVars:



# envVarGroups:
# - name: flask-postgres-api-settings
#   envVars:
#   - key: ENV
#     value: production
#   - key: FLASK_APP
#     value: src/main.py